/*
 * WARNING: do not edit!
 * Generated by Makefile from providers/common/der/der_composite_gen.c.in
 *
 * Copyright 2024-2025 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#include "prov/composite.h"

/* Well known OIDs precompiled */
/* clang-format off */

/*
 * id-mldsa44-rsa2048-pss-sha256 OBJECT IDENTIFIER ::= { sigAlgs 37 }
 */
const unsigned char ossl_der_oid_id_mldsa44_rsa2048_pss_sha256[DER_OID_SZ_id_mldsa44_rsa2048_pss_sha256] = {
    DER_OID_V_id_mldsa44_rsa2048_pss_sha256
};

/*
 * id-mldsa44-rsa2048-pkcs15-sha256 OBJECT IDENTIFIER ::= { sigAlgs 38 }
 */
const unsigned char ossl_der_oid_id_mldsa44_rsa2048_pkcs15_sha256[DER_OID_SZ_id_mldsa44_rsa2048_pkcs15_sha256] = {
    DER_OID_V_id_mldsa44_rsa2048_pkcs15_sha256
};

/*
 * id-mldsa44-ed25519-sha512 OBJECT IDENTIFIER ::= { sigAlgs 39 }
 */
const unsigned char ossl_der_oid_id_mldsa44_ed25519_sha512[DER_OID_SZ_id_mldsa44_ed25519_sha512] = {
    DER_OID_V_id_mldsa44_ed25519_sha512
};

/*
 * id-mldsa44-ecdsa-p256-sha256 OBJECT IDENTIFIER ::= { sigAlgs 40 }
 */
const unsigned char ossl_der_oid_id_mldsa44_ecdsa_p256_sha256[DER_OID_SZ_id_mldsa44_ecdsa_p256_sha256] = {
    DER_OID_V_id_mldsa44_ecdsa_p256_sha256
};

/*
 * id-mldsa65-rsa3072-pss-sha512 OBJECT IDENTIFIER ::= { sigAlgs 41 }
 */
const unsigned char ossl_der_oid_id_mldsa65_rsa3072_pss_sha512[DER_OID_SZ_id_mldsa65_rsa3072_pss_sha512] = {
    DER_OID_V_id_mldsa65_rsa3072_pss_sha512
};

/*
 * id-mldsa65-rsa3072-pkcs15-sha512 OBJECT IDENTIFIER ::= { sigAlgs 42 }
 */
const unsigned char ossl_der_oid_id_mldsa65_rsa3072_pkcs15_sha512[DER_OID_SZ_id_mldsa65_rsa3072_pkcs15_sha512] = {
    DER_OID_V_id_mldsa65_rsa3072_pkcs15_sha512
};

/*
 * id-mldsa65-rsa4096-pss-sha512 OBJECT IDENTIFIER ::= { sigAlgs 43 }
 */
const unsigned char ossl_der_oid_id_mldsa65_rsa4096_pss_sha512[DER_OID_SZ_id_mldsa65_rsa4096_pss_sha512] = {
    DER_OID_V_id_mldsa65_rsa4096_pss_sha512
};

/*
 * id-mldsa65-rsa4096-pkcs15-sha512 OBJECT IDENTIFIER ::= { sigAlgs 44 }
 */
const unsigned char ossl_der_oid_id_mldsa65_rsa4096_pkcs15_sha512[DER_OID_SZ_id_mldsa65_rsa4096_pkcs15_sha512] = {
    DER_OID_V_id_mldsa65_rsa4096_pkcs15_sha512
};

/*
 * id-mldsa65-ecdsa-p256-sha512 OBJECT IDENTIFIER ::= { sigAlgs 45 }
 */
const unsigned char ossl_der_oid_id_mldsa65_ecdsa_p256_sha512[DER_OID_SZ_id_mldsa65_ecdsa_p256_sha512] = {
    DER_OID_V_id_mldsa65_ecdsa_p256_sha512
};

/*
 * id-mldsa65-ecdsa-p384-sha512 OBJECT IDENTIFIER ::= { sigAlgs 46 }
 */
const unsigned char ossl_der_oid_id_mldsa65_ecdsa_p384_sha512[DER_OID_SZ_id_mldsa65_ecdsa_p384_sha512] = {
    DER_OID_V_id_mldsa65_ecdsa_p384_sha512
};

/*
 * id-mldsa65-ecdsa-brainpoolP256r1-sha512 OBJECT IDENTIFIER ::= { sigAlgs 47 }
 */
const unsigned char ossl_der_oid_id_mldsa65_ecdsa_brainpoolP256r1_sha512[DER_OID_SZ_id_mldsa65_ecdsa_brainpoolP256r1_sha512] = {
    DER_OID_V_id_mldsa65_ecdsa_brainpoolP256r1_sha512
};

/*
 * id-mldsa65-ed25519-sha512 OBJECT IDENTIFIER ::= { sigAlgs 48 }
 */
const unsigned char ossl_der_oid_id_mldsa65_ed25519_sha512[DER_OID_SZ_id_mldsa65_ed25519_sha512] = {
    DER_OID_V_id_mldsa65_ed25519_sha512
};

/*
 * id-mldsa87-ecdsa-p384-sha512 OBJECT IDENTIFIER ::= { sigAlgs 49 }
 */
const unsigned char ossl_der_oid_id_mldsa87_ecdsa_p384_sha512[DER_OID_SZ_id_mldsa87_ecdsa_p384_sha512] = {
    DER_OID_V_id_mldsa87_ecdsa_p384_sha512
};

/*
 * id-mldsa87-ecdsa-brainpoolp384r1-sha512 OBJECT IDENTIFIER ::= { sigAlgs 50 }
 */
const unsigned char ossl_der_oid_id_mldsa87_ecdsa_brainpoolp384r1_sha512[DER_OID_SZ_id_mldsa87_ecdsa_brainpoolp384r1_sha512] = {
    DER_OID_V_id_mldsa87_ecdsa_brainpoolp384r1_sha512
};

/*
 * id-mldsa87-ed448-shake256 OBJECT IDENTIFIER ::= { sigAlgs 51 }
 */
const unsigned char ossl_der_oid_id_mldsa87_ed448_shake256[DER_OID_SZ_id_mldsa87_ed448_shake256] = {
    DER_OID_V_id_mldsa87_ed448_shake256
};

/*
 * id-mldsa87-rsa3072-pss-sha512 OBJECT IDENTIFIER ::= { sigAlgs 52 }
 */
const unsigned char ossl_der_oid_id_mldsa87_rsa3072_pss_sha512[DER_OID_SZ_id_mldsa87_rsa3072_pss_sha512] = {
    DER_OID_V_id_mldsa87_rsa3072_pss_sha512
};

/*
 * id-mldsa87-rsa4096-pss-sha512 OBJECT IDENTIFIER ::= { sigAlgs 53 }
 */
const unsigned char ossl_der_oid_id_mldsa87_rsa4096_pss_sha512[DER_OID_SZ_id_mldsa87_rsa4096_pss_sha512] = {
    DER_OID_V_id_mldsa87_rsa4096_pss_sha512
};

/*
 * id-mldsa87-ecdsa-p521-sha512 OBJECT IDENTIFIER ::= { sigAlgs 54 }
 */
const unsigned char ossl_der_oid_id_mldsa87_ecdsa_p521_sha512[DER_OID_SZ_id_mldsa87_ecdsa_p521_sha512] = {
    DER_OID_V_id_mldsa87_ecdsa_p521_sha512
};

/* clang-format on */
