/*
 * WARNING: do not edit!
 * Generated by Makefile from providers/common/include/prov/composite.h.in
 *
 * Copyright 2020-2021 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef PROV_COMPOSITE_H
# define PROV_COMPOSITE_H

#include "internal/der.h"
#include "crypto/ml_dsa.h"
#include "prov/provider_ctx.h"

#define COMPOSITE_PREFIX "436F6D706F73697465416C676F726974686D5369676E61747572657332303235"

/* Well known OIDs precompiled */

/*
 * id-mldsa44-rsa2048-pss-sha256 OBJECT IDENTIFIER ::= { sigAlgs 37 }
 */
#define DER_OID_V_id_mldsa44_rsa2048_pss_sha256 DER_P_OBJECT, 8, 0x2B, 0x06, 0x01, 0x05, 0x05, 0x07, 0x06, 0x25
#define DER_OID_SZ_id_mldsa44_rsa2048_pss_sha256 10
extern const unsigned char ossl_der_oid_id_mldsa44_rsa2048_pss_sha256[DER_OID_SZ_id_mldsa44_rsa2048_pss_sha256];

/*
 * id-mldsa44-rsa2048-pkcs15-sha256 OBJECT IDENTIFIER ::= { sigAlgs 38 }
 */
#define DER_OID_V_id_mldsa44_rsa2048_pkcs15_sha256 DER_P_OBJECT, 8, 0x2B, 0x06, 0x01, 0x05, 0x05, 0x07, 0x06, 0x26
#define DER_OID_SZ_id_mldsa44_rsa2048_pkcs15_sha256 10
extern const unsigned char ossl_der_oid_id_mldsa44_rsa2048_pkcs15_sha256[DER_OID_SZ_id_mldsa44_rsa2048_pkcs15_sha256];

/*
 * id-mldsa44-ed25519-sha512 OBJECT IDENTIFIER ::= { sigAlgs 39 }
 */
#define DER_OID_V_id_mldsa44_ed25519_sha512 DER_P_OBJECT, 8, 0x2B, 0x06, 0x01, 0x05, 0x05, 0x07, 0x06, 0x27
#define DER_OID_SZ_id_mldsa44_ed25519_sha512 10
extern const unsigned char ossl_der_oid_id_mldsa44_ed25519_sha512[DER_OID_SZ_id_mldsa44_ed25519_sha512];

/*
 * id-mldsa44-ecdsa-p256-sha256 OBJECT IDENTIFIER ::= { sigAlgs 40 }
 */
#define DER_OID_V_id_mldsa44_ecdsa_p256_sha256 DER_P_OBJECT, 8, 0x2B, 0x06, 0x01, 0x05, 0x05, 0x07, 0x06, 0x28
#define DER_OID_SZ_id_mldsa44_ecdsa_p256_sha256 10
extern const unsigned char ossl_der_oid_id_mldsa44_ecdsa_p256_sha256[DER_OID_SZ_id_mldsa44_ecdsa_p256_sha256];

/*
 * id-mldsa65-rsa3072-pss-sha512 OBJECT IDENTIFIER ::= { sigAlgs 41 }
 */
#define DER_OID_V_id_mldsa65_rsa3072_pss_sha512 DER_P_OBJECT, 8, 0x2B, 0x06, 0x01, 0x05, 0x05, 0x07, 0x06, 0x29
#define DER_OID_SZ_id_mldsa65_rsa3072_pss_sha512 10
extern const unsigned char ossl_der_oid_id_mldsa65_rsa3072_pss_sha512[DER_OID_SZ_id_mldsa65_rsa3072_pss_sha512];

/*
 * id-mldsa65-rsa3072-pkcs15-sha512 OBJECT IDENTIFIER ::= { sigAlgs 42 }
 */
#define DER_OID_V_id_mldsa65_rsa3072_pkcs15_sha512 DER_P_OBJECT, 8, 0x2B, 0x06, 0x01, 0x05, 0x05, 0x07, 0x06, 0x2A
#define DER_OID_SZ_id_mldsa65_rsa3072_pkcs15_sha512 10
extern const unsigned char ossl_der_oid_id_mldsa65_rsa3072_pkcs15_sha512[DER_OID_SZ_id_mldsa65_rsa3072_pkcs15_sha512];

/*
 * id-mldsa65-rsa4096-pss-sha512 OBJECT IDENTIFIER ::= { sigAlgs 43 }
 */
#define DER_OID_V_id_mldsa65_rsa4096_pss_sha512 DER_P_OBJECT, 8, 0x2B, 0x06, 0x01, 0x05, 0x05, 0x07, 0x06, 0x2B
#define DER_OID_SZ_id_mldsa65_rsa4096_pss_sha512 10
extern const unsigned char ossl_der_oid_id_mldsa65_rsa4096_pss_sha512[DER_OID_SZ_id_mldsa65_rsa4096_pss_sha512];

/*
 * id-mldsa65-rsa4096-pkcs15-sha512 OBJECT IDENTIFIER ::= { sigAlgs 44 }
 */
#define DER_OID_V_id_mldsa65_rsa4096_pkcs15_sha512 DER_P_OBJECT, 8, 0x2B, 0x06, 0x01, 0x05, 0x05, 0x07, 0x06, 0x2C
#define DER_OID_SZ_id_mldsa65_rsa4096_pkcs15_sha512 10
extern const unsigned char ossl_der_oid_id_mldsa65_rsa4096_pkcs15_sha512[DER_OID_SZ_id_mldsa65_rsa4096_pkcs15_sha512];

/*
 * id-mldsa65-ecdsa-p256-sha512 OBJECT IDENTIFIER ::= { sigAlgs 45 }
 */
#define DER_OID_V_id_mldsa65_ecdsa_p256_sha512 DER_P_OBJECT, 8, 0x2B, 0x06, 0x01, 0x05, 0x05, 0x07, 0x06, 0x2D
#define DER_OID_SZ_id_mldsa65_ecdsa_p256_sha512 10
extern const unsigned char ossl_der_oid_id_mldsa65_ecdsa_p256_sha512[DER_OID_SZ_id_mldsa65_ecdsa_p256_sha512];

/*
 * id-mldsa65-ecdsa-p384-sha512 OBJECT IDENTIFIER ::= { sigAlgs 46 }
 */
#define DER_OID_V_id_mldsa65_ecdsa_p384_sha512 DER_P_OBJECT, 8, 0x2B, 0x06, 0x01, 0x05, 0x05, 0x07, 0x06, 0x2E
#define DER_OID_SZ_id_mldsa65_ecdsa_p384_sha512 10
extern const unsigned char ossl_der_oid_id_mldsa65_ecdsa_p384_sha512[DER_OID_SZ_id_mldsa65_ecdsa_p384_sha512];

/*
 * id-mldsa65-ecdsa-brainpoolP256r1-sha512 OBJECT IDENTIFIER ::= { sigAlgs 47 }
 */
#define DER_OID_V_id_mldsa65_ecdsa_brainpoolP256r1_sha512 DER_P_OBJECT, 8, 0x2B, 0x06, 0x01, 0x05, 0x05, 0x07, 0x06, 0x2F
#define DER_OID_SZ_id_mldsa65_ecdsa_brainpoolP256r1_sha512 10
extern const unsigned char ossl_der_oid_id_mldsa65_ecdsa_brainpoolP256r1_sha512[DER_OID_SZ_id_mldsa65_ecdsa_brainpoolP256r1_sha512];

/*
 * id-mldsa65-ed25519-sha512 OBJECT IDENTIFIER ::= { sigAlgs 48 }
 */
#define DER_OID_V_id_mldsa65_ed25519_sha512 DER_P_OBJECT, 8, 0x2B, 0x06, 0x01, 0x05, 0x05, 0x07, 0x06, 0x30
#define DER_OID_SZ_id_mldsa65_ed25519_sha512 10
extern const unsigned char ossl_der_oid_id_mldsa65_ed25519_sha512[DER_OID_SZ_id_mldsa65_ed25519_sha512];

/*
 * id-mldsa87-ecdsa-p384-sha512 OBJECT IDENTIFIER ::= { sigAlgs 49 }
 */
#define DER_OID_V_id_mldsa87_ecdsa_p384_sha512 DER_P_OBJECT, 8, 0x2B, 0x06, 0x01, 0x05, 0x05, 0x07, 0x06, 0x31
#define DER_OID_SZ_id_mldsa87_ecdsa_p384_sha512 10
extern const unsigned char ossl_der_oid_id_mldsa87_ecdsa_p384_sha512[DER_OID_SZ_id_mldsa87_ecdsa_p384_sha512];

/*
 * id-mldsa87-ecdsa-brainpoolp384r1-sha512 OBJECT IDENTIFIER ::= { sigAlgs 50 }
 */
#define DER_OID_V_id_mldsa87_ecdsa_brainpoolp384r1_sha512 DER_P_OBJECT, 8, 0x2B, 0x06, 0x01, 0x05, 0x05, 0x07, 0x06, 0x32
#define DER_OID_SZ_id_mldsa87_ecdsa_brainpoolp384r1_sha512 10
extern const unsigned char ossl_der_oid_id_mldsa87_ecdsa_brainpoolp384r1_sha512[DER_OID_SZ_id_mldsa87_ecdsa_brainpoolp384r1_sha512];

/*
 * id-mldsa87-ed448-shake256 OBJECT IDENTIFIER ::= { sigAlgs 51 }
 */
#define DER_OID_V_id_mldsa87_ed448_shake256 DER_P_OBJECT, 8, 0x2B, 0x06, 0x01, 0x05, 0x05, 0x07, 0x06, 0x33
#define DER_OID_SZ_id_mldsa87_ed448_shake256 10
extern const unsigned char ossl_der_oid_id_mldsa87_ed448_shake256[DER_OID_SZ_id_mldsa87_ed448_shake256];

/*
 * id-mldsa87-rsa3072-pss-sha512 OBJECT IDENTIFIER ::= { sigAlgs 52 }
 */
#define DER_OID_V_id_mldsa87_rsa3072_pss_sha512 DER_P_OBJECT, 8, 0x2B, 0x06, 0x01, 0x05, 0x05, 0x07, 0x06, 0x34
#define DER_OID_SZ_id_mldsa87_rsa3072_pss_sha512 10
extern const unsigned char ossl_der_oid_id_mldsa87_rsa3072_pss_sha512[DER_OID_SZ_id_mldsa87_rsa3072_pss_sha512];

/*
 * id-mldsa87-rsa4096-pss-sha512 OBJECT IDENTIFIER ::= { sigAlgs 53 }
 */
#define DER_OID_V_id_mldsa87_rsa4096_pss_sha512 DER_P_OBJECT, 8, 0x2B, 0x06, 0x01, 0x05, 0x05, 0x07, 0x06, 0x35
#define DER_OID_SZ_id_mldsa87_rsa4096_pss_sha512 10
extern const unsigned char ossl_der_oid_id_mldsa87_rsa4096_pss_sha512[DER_OID_SZ_id_mldsa87_rsa4096_pss_sha512];

/*
 * id-mldsa87-ecdsa-p521-sha512 OBJECT IDENTIFIER ::= { sigAlgs 54 }
 */
#define DER_OID_V_id_mldsa87_ecdsa_p521_sha512 DER_P_OBJECT, 8, 0x2B, 0x06, 0x01, 0x05, 0x05, 0x07, 0x06, 0x36
#define DER_OID_SZ_id_mldsa87_ecdsa_p521_sha512 10
extern const unsigned char ossl_der_oid_id_mldsa87_ecdsa_p521_sha512[DER_OID_SZ_id_mldsa87_ecdsa_p521_sha512];


typedef struct {
  ML_DSA_KEY *ml_dsa_key;
  EVP_PKEY *classic_key;
} COMPOSITE_KEY;

typedef struct {
    OSSL_LIB_CTX *libctx;
    const char *alg;
    const unsigned char *oid;
    size_t oid_sz;
    uint8_t context_string[255]; /* ML_DSA_MAX_CONTEXT_STRING_LEN */
    size_t context_string_len;
    const char *prehash_alg;
    size_t prehash_len;

    /* ML DSA */
    PROV_CTX *mldsa_ctx;

    /* CLASSIC */
    EVP_PKEY_CTX *classic_ctx;

    COMPOSITE_KEY *key;
} PROV_COMPOSITE_CTX;

#endif /* PROV_COMPOSITE_H */